-- NOTE:
-- This migration originally contained data updates that assumed "tasks" already
-- existed, but its timestamp is earlier than the initial schema migration.
-- Keep this migration as an intentional no-op and run status normalization in a
-- later migration once all task tables exist.
